# Generated by Django 3.0.4 on 2020-05-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0003_sectionb_type_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiona',
            name='a2_keywords',
            field=models.TextField(default='TODO'),
            preserve_default=False,
        ),
    ]
