# Generated by Django 3.1.3 on 2021-01-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0004_sectiona_a2_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionc',
            name='c1',
            field=models.TextField(default='For __category__ projects, at least one QA audit is required per ORD QA Policy titled Use of the Graded Approach for Quality Assurance of Research.  A technical systems audit TSA will be completed within one year of the initial QA Project Plan approval date for this research effort. The TSA will be conducted in accordance with ORD QA Policy titled Audits of Technical and Quality Systems. Draft publications resulting from this project will undergo ORD clearance in STICS prior to dissemination as required by ORD Policy titled ORD Clearance Policy and Procedures and CESER SOP titled Standard Operating Procedure for Product Clearance.'),
        ),
        migrations.AddField(
            model_name='sectionc',
            name='c2',
            field=models.TextField(default='Results of QA audits will be reported in accordance with ORD QA Policy titled Audits of Technical and Quality Systems.  Implementation of corrective actions for audit findings will be verified by the QA Manager, and status of implementation tracked through closure. Required approvals for draft publications undergoing ORD clearance is documented in STICS.'),
        ),
    ]
