# Generated by Django 4.1.7 on 2023-03-02 19:50

import constants.utils
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qapp_builder', '0005_auto_20210104_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionb',
            name='b1_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b1_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b6_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='A:\\GQC\\git\\projects\\epa\\QAPPBuilder\\QAPPBuilder\\qapp_builder/media\\uploads'), upload_to=constants.utils.get_attachment_storage_path)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
