# Generated by Django 4.1.7 on 2023-04-04 19:10

import constants.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qapp_builder', '0006_sectionb_b1_6_sectionb_b1_7_sectionb_b5_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionb',
            name='b2_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b2_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b4_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b4_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b4_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_1_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_1_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_2_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_2_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_2_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_2_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_2_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_2_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_2_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b5_2_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b6_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionb',
            name='b6_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/uploads', location='A:\\GQC\\git\\projects\\epa\\qappbuilder\\QAPPBuilder\\qapp_builder/media\\uploads'), upload_to=constants.utils.get_attachment_storage_path),
        ),
    ]
